
const { SlashCommandBuilder } = require('@discordjs/builders');


module.exports = {
	data: new SlashCommandBuilder()
		.setName('truth')
		.setDescription('A Truth And Dare Command'),
	async execute(interaction,  client, Discord) {
        let flip1= ["who do you hate most among your discord friends","what's one illegal thing that you own or have done","name one song you like and one song you hate","do you like the server owners or mods","What is the biggest lie you have ever told?","What is your deepest darkest fear?","When was the last time you lied","What’s the most embarrassing thing you’ve ever done?","What’s the worst thing you’ve ever done?","What’s the biggest misconception about you?","What’s the worst time you let someone take the blame for something you did?","What’s your biggest regret?","What is the most embarrassing series of texts you have on your phone?","Do you have a hidden talent?","What is the stupidest thing you've ever done?","Who is your crush?","What’s something you’re glad your parents doesn’t know about you?","Who was your first celebrity crush?","Have you ever cheated in an exam?","What’s the biggest mistake you’ve ever made?","Who would you like to kiss here?","What’s the worst thing anyone’s ever done to you?","What’s the most trouble you’ve been in?","Who have you loved but they didn’t love you back?","What was the cruellest joke you played on someone","What is the most embarrassing nickname you have ever had?","what is your nickname at your house","Tell me something you don’t want me to know","What's the worst game","Who do you like the most in your discord friends","If you could say anything to your crush right now, what would it be?","How old were you when you had your first kiss?","What's one thing you've done that people here would judge you for?","Who has the best sense of style?","How old were you when you had your first crush?","If you had only $10 left to your name, how would you spend it?","What is your biggest insecurity?","Do you have trust issues?","If you could get one of your teachers/managers/bosses fired, who would it be?","What's your favorite thing about your crush?","Have you ever embarrassed yourself in front of a crush?","Who is the most innocent person in this server?","Who here is the hopeless romantic?","What was one unrealistic dream you had ?","have you stalked the chat","Who here do you trust the least?","who do you think like a hacker here","If you could be one person in this server, who would you be?","Do you consider yourself introvert","What is the last letter in the name of your crush?","Would you ever get back with an ex?","Do you have a social media account that you hide?","Do you think you have a chance at love?"
        ,"If you had to kiss one person here, who would you pick?","What is your least favorite music genre?","favorite music genre","top 3 songs","to 3 movies","rate a person on there discord pfp","Have you ever done something that you wish you apologized for when you had the chance?","biggest fear","How many selfies do you take per day?","do you send different snaps to different person so they dont judge you ","favorite color","favorite food","favorite place","how many photos do you have on your phone","How much would you do to get your dream partner?","Have you ever fallen in love with your best friend?","Have you ever had a crush on a friend's partner?","What’s something you love to do with your friends that you’d never do in front of your partner?","Do you think you're attractive?","Out of the last three people you texted, if you had to kiss one of them who would you pick?","who is your last dm","Name of the person you called recently ","Best friend","When was the last time you made someone cry?","Do you think people are scared from you","If you could learn the way you die, would you do it","Will you die for them","How has the past year been for you?","Do you like using this bot ? (invite click here)[https://discord.com/api/oauth2/authorize?client_id=780294659977117718&permissions=260117621879&scope=applications.commands%20bot] ","What's the first letter of your crush's name?","What was the most awkward part of a date you have been on?","best game you played till now","If you had to kill one person here, who would it be?"];
        const flip2 = flip1[Math.floor(Math.random() * flip1.length)];
        const flipped = new Discord.MessageEmbed()
    .setColor('#0cfcf2')
    .setTitle("Truth", )
    .setDescription(` ${flip2}`) 
    .setTimestamp()
    .setFooter(interaction.user.tag);
		await interaction.reply({embeds:[flipped]}).catch(error => { console.log(error , `truth line 19`)});
	},
};